<a href="https://colab.research.google.com/github/dareoyeleke/SQL-ENGINEERING/blob/main/Cohort_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql
SELECT
  customerkey,
  orderkey,
  linenumber,
  (quantity * netprice * exchangerate) as net_revenue,
  AVG (quantity * netprice * exchangerate) OVER() avg_net_revenue_all_orders,
  AVG (quantity * netprice * exchangerate) OVER( PARTITION BY customerkey) avg_net_revenue_this_orders
FROM sales
ORDER BY customerkey
LIMIT 10

In [ ]:
%%sql
/*
  Ran in order of customer key orders the index, order date per customer key follows, order rank from 1 forward follows highest revenue to lowest revenue, customer running
  revenue is ordered by indivdual day, total revenue is total sum for all orders, ROW NUMBER() has to be used witH ORDER BY in OVER() window function to order row rank
*/
SELECT
  customerkey,
  orderdate,
  (quantity * netprice * exchangerate) as net_revenue,
  ROW_NUMBER() OVER(
    PARTITION BY customerkey
    ORDER BY quantity * netprice * exchangerate DESC
  ) as order_rank,
  SUM (quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) as customer_running_revenue,
  SUM (quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
  ) as customer_total_revenue,
 (quantity * netprice * exchangerate)/SUM(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
  ) * 100 as pct_of_revenue
FROM sales
ORDER BY customerkey, orderdate
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderdate,net_revenue,order_rank,customer_running_revenue,customer_total_revenue,pct_of_revenue
0,15,2021-03-08,2217.41,1,2217.41,2217.41,100.00
1,180,2018-07-28,525.31,2,525.31,2510.22,20.93
2,180,2023-08-28,1913.55,1,2510.22,2510.22,76.23
3,180,2023-08-28,71.36,3,2510.22,2510.22,2.84
4,185,2019-06-01,1395.52,1,1395.52,1395.52,100.00
5,243,2016-05-19,287.67,1,287.67,287.67,100.00
6,387,2018-12-21,619.77,3,2370.54,4655.84,13.31
7,387,2018-12-21,1608.10,1,2370.54,4655.84,34.54
8,387,2018-12-21,97.05,7,2370.54,4655.84,2.08
9,387,2018-12-21,45.62,8,2370.54,4655.84,0.98

In [ ]:
%%sql

SELECT
    orderdate,
    orderkey * 10 + linenumber as order_line_item,
    (quantity * netprice * exchangerate) as net_revenue,
    SUM(quantity * netprice * exchangerate) OVER(
      PARTITION BY orderdate
    ) as daily_net_revenue,
    (quantity * netprice * exchangerate) /  SUM(quantity * netprice * exchangerate) OVER(
      PARTITION BY orderdate
    ) * 100 as pct_of_revenue
FROM
    sales
ORDER BY orderdate, net_revenue DESC
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  order_line_item  net_revenue  daily_net_revenue  pct_of_revenue
0  2015-01-01            10043      2395.10           11640.80           20.58
1  2015-01-01            10061      1552.32           11640.80           13.34
2  2015-01-01            10022      1302.91           11640.80           11.19
3  2015-01-01            10020      1146.75           11640.80            9.85
4  2015-01-01            10050       975.16           11640.80            8.38
5  2015-01-01            10021       950.25           11640.80            8.16
6  2015-01-01            10041       578.52           11640.80            4.97
7  2015-01-01            10081       574.05           11640.80            4.93
8  2015-01-01            10001       423.28           11640.80            3.64
9  2015-01-01            10040       263.11           11640.80            2.26

In [ ]:
%%sql
WITH yearly_cohort as (
  SELECT DISTINCT
    customerkey,
    EXTRACT (YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) as cohort_year
  FROM sales )
SELECT
  yc.cohort_year,
  EXTRACT (YEAR FROM s.orderdate) as purchase_year,
  SUM(s.quantity * s.netprice * s.exchangerate) as net_revenue
FROM sales s
LEFT JOIN yearly_cohort yc ON s.customerkey = yc.customerkey
GROUP BY yc.cohort_year, purchase_year
ORDER BY yc.cohort_year

In [ ]:
%%sql
WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT (YEAR FROM MIN(orderdate) OVER ( PARTITION BY customerkey)) as cohort_year,
    EXTRACT ( YEAR FROM orderdate) as purchase_year
  FROM sales
)
SELECT DISTINCT
  cohort_year,
  purchase_year,
  COUNT(customerkey) OVER(PARTITION BY cohort_year, purchase_year) as num_customers
FROM yearly_cohort
ORDER BY cohort_year, purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  num_customers
0         2015          2015           2825
1         2015          2016            126
2         2015          2017            149
3         2015          2018            348
4         2015          2019            388
5         2015          2020            171
6         2015          2021            295
7         2015          2022            600
8         2015          2023            499
9         2015          2024            146
10        2016          2016           3397
11        2016          2017            174
12        2016          2018            374
13        2016          2019            457
14        2016          2020            205
15        2016          2021            336
16        2016          2022            746
17        2016          2023            573
18        2016          2024            183
19        2017          2017           4068
20        2017          2018            473
21        2017          2019            570
22        2017          2020            251
23        2017          2021            450
24        2017          2022            943
25        2017          2023            738
26        2017          2024            246
27        2018          2018           7446
28        2018          2019           1081
29        2018          2020            475
30        2018          2021            779
31        2018          2022           1644
32        2018          2023           1407
33        2018          2024            426
34        2019          2019           7755
35        2019          2020            523
36        2019          2021            873
37        2019          2022           1700
38        2019          2023           1439
39        2019          2024            370
40        2020          2020           3031
41        2020          2021            358
42        2020          2022            694
43        2020          2023            547
44        2020          2024            163
45        2021          2021           4663
46        2021          2022           1051
47        2021          2023            889
48        2021          2024            268
49        2022          2022           9010
50        2022          2023           1764
51        2022          2024            561
52        2023          2023           5890
53        2023          2024            332
54        2024          2024           1402

In [ ]:
%%sql

SELECT  column_name
FROM information_schema.columns
WHERE table_schema ='public'
  and   table_name = 'sales'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

13 rows affected.

     column_name
0       orderkey
1     linenumber
2      orderdate
3   deliverydate
4    customerkey
5       storekey
6     productkey
7       quantity
8      unitprice
9       netprice
10      unitcost
11  currencycode
12  exchangerate

In [ ]:
%%sql

SELECT
  COUNT (*) AS total_rows
FROM
  sales;

SHOW search_path

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

1 rows affected.

       search_path
0  "$user", public

In [ ]:
%%sql

WITH yearly_cohort AS

(
SELECT
  customerkey,
  EXTRACT (YEAR FROM MIN(orderdate)) AS cohort_year,
  SUM(quantity * netprice * exchangerate) AS customer_ltv
FROM
  sales
GROUP BY customerkey
ORDER BY cohort_year, customerkey
)

SELECT
  *,
  AVG (customer_ltv) OVER (PARTITION BY cohort_year) AS avg_customer_ltv
FROM
  yearly_cohort

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_customer_ltv
0             4376        2015        182.00           5271.59
1             4403        2015       9530.35           5271.59
2             4925        2015       6078.08           5271.59
3             5729        2015        192.16           5271.59
4             6048        2015       1903.89           5271.59
...            ...         ...           ...               ...
49482      2093965        2024        475.22           2037.55
49483      2095129        2024        156.00           2037.55
49484      2095691        2024        326.00           2037.55
49485      2096470        2024        535.78           2037.55
49486      2097541        2024       1143.15           2037.55

[49487 rows x 4 columns]

In [ ]:
%%sql

  SELECT
  customerkey,
  orderdate,
  ( quantity * netprice * exchangerate) as net_revenue,
  COUNT(*) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate
    ) as running_order_count,
  AVG(quantity * netprice * exchangerate) OVER(
    PARTITION BY customerkey
    ORDER BY orderdate
  ) as running_avg_revenue
FROM
  sales
LIMIT 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,1913.55,3,836.74
3,180,2023-08-28,71.36,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
5,243,2016-05-19,287.67,1,287.67
6,387,2018-12-21,97.05,4,592.64
7,387,2018-12-21,1608.10,4,592.64
8,387,2018-12-21,45.62,4,592.64
9,387,2018-12-21,619.77,4,592.64
10,387,2021-10-30,1265.56,5,727.22
11,387,2023-11-16,30.51,9,517.32
12,387,2023-11-16,446.44,9,517.32
13,387,2023-11-16,180.35,9,517.32
14,387,2023-11-16,362.44,9,517.32
15,406,2021-11-06,762.69,2,1096.71
16,406,2021-11-06,1430.73,2,1096.71
17,545,2023-07-01,1475.91,6,591.91
18,545,2023-07-01,266.21,6,591.91
19,545,2023-07-01,79.67,6,591.91

In [ ]:
%%sql
/*    ROW_NUMBER AND RANK() both need to have an order by, but as RANK() suggests over ROW_NUMBER, ROW_NUMBER gives individual values in increments of 1 for each row,
  while RANK() gives the same value to rows of the same value and skips a rank for every repeated value, e.g if there's 3 values of red at rank 3, the next rank is 6,
  because rank 4 and 5 went to the other tow values of red at rank 3. DENSE_RANK() gives rank by ORDER BY() wih similar rows, but doesn't skip numbers while ranking.
  With DENSE_RANK(), similar rows get the same rank, but doesn't skip value for the next rank.
*/
SELECT
  customerkey,
  COUNT(*) AS total_orders,
  ROW_NUMBER() OVER( ORDER BY COUNT(*) DESC) AS total_orders_row_num,
  RANK() OVER( ORDER BY COUNT(*) DESC) AS total_orders_rank,
  DENSE_RANK() OVER( ORDER BY COUNT(*) DESC) AS total_orders_dense_rank
FROM sales
GROUP BY customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders,total_orders_row_num,total_orders_rank,total_orders_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6

In [ ]:
%%sql
/*    Here I used group by month, because grouping bu orderdate printed every individual date across the month in the first column,
  grouping by month makes it group by every single month for the year specified instead, big difference. FIRST_VALUE() ORDER BY(),
  AND LAST_VALUE() ORDER BY are vastly different, NTH_VALUE() ORDER BY(), follows the same procedure. LAG() values print out values
  of previous month, however LAG can be increased by adding integer for LAG() condition as thus LAG(net_revenue, 2) to show how many
  months in this case since we ORDER BY month in OVER() to print out, same thing applies to LEAD().
*/
WITH monthly_revenue_2023 AS
(
SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM( quantity * netprice * exchangerate) as net_revenue
FROM
  sales
WHERE EXTRACT(YEAR FROM orderdate) = '2023'
GROUP BY month
)

SELECT
  *,
  LAG(net_revenue) OVER(ORDER BY month) as previous_month_revenue,
  LEAD(net_revenue) OVER(ORDER BY month) as next_month_revenue,
  FIRST_VALUE(net_revenue) OVER(ORDER BY month) as first_month_revenue,
  LAST_VALUE(net_revenue) OVER(ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as last_month_revenue,
  NTH_VALUE(net_revenue, 3) OVER(ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as third_month_revenue
FROM monthly_revenue_2023 mr

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,previous_month_revenue,next_month_revenue,first_month_revenue,last_month_revenue,third_month_revenue
0,2023-01,3664431.34,NaN,4465204.57,3664431.34,2928550.93,2244316.52
1,2023-02,4465204.57,3664431.34,2244316.52,3664431.34,2928550.93,2244316.52
2,2023-03,2244316.52,4465204.57,1162796.16,3664431.34,2928550.93,2244316.52
3,2023-04,1162796.16,2244316.52,2943005.99,3664431.34,2928550.93,2244316.52
4,2023-05,2943005.99,1162796.16,2864500.03,3664431.34,2928550.93,2244316.52
5,2023-06,2864500.03,2943005.99,2337639.34,3664431.34,2928550.93,2244316.52
6,2023-07,2337639.34,2864500.03,2623919.79,3664431.34,2928550.93,2244316.52
7,2023-08,2623919.79,2337639.34,2622774.85,3664431.34,2928550.93,2244316.52
8,2023-09,2622774.85,2623919.79,2551322.61,3664431.34,2928550.93,2244316.52
9,2023-10,2551322.61,2622774.85,2700103.38,3664431.34,2928550.93,2244316.52
10,2023-11,2700103.38,2551322.61,2928550.93,3664431.34,2928550.93,2244316.52
11,2023-12,2928550.93,2700103.38,NaN,3664431.34,2928550.93,2244316.52

In [ ]:
%%sql

WITH monthly_revenue_2023 AS
(
SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS month,
  SUM( quantity * netprice * exchangerate) as net_revenue
FROM
  sales
WHERE EXTRACT(YEAR FROM orderdate) = '2023'
GROUP BY month
)

SELECT
  *,
  LAG(net_revenue) OVER(ORDER BY month) as previous_month_revenue,
  LEAD(net_revenue) OVER(ORDER BY month) as next_month_revenue,
  (net_revenue - LAG(net_revenue) OVER(ORDER BY month)) / LAG(net_revenue) OVER(ORDER BY month) * 100 as monthly_revenue_pct_change
FROM monthly_revenue_2023 mr

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,previous_month_revenue,next_month_revenue,monthly_revenue_pct_change
0,2023-01,3664431.34,NaN,4465204.57,NaN
1,2023-02,4465204.57,3664431.34,2244316.52,21.85
2,2023-03,2244316.52,4465204.57,1162796.16,-49.74
3,2023-04,1162796.16,2244316.52,2943005.99,-48.19
4,2023-05,2943005.99,1162796.16,2864500.03,153.10
5,2023-06,2864500.03,2943005.99,2337639.34,-2.67
6,2023-07,2337639.34,2864500.03,2623919.79,-18.39
7,2023-08,2623919.79,2337639.34,2622774.85,12.25
8,2023-09,2622774.85,2623919.79,2551322.61,-0.04
9,2023-10,2551322.61,2622774.85,2700103.38,-2.72
10,2023-11,2700103.38,2551322.61,2928550.93,5.83
11,2023-12,2928550.93,2700103.38,NaN,8.46

In [ ]:
%%sql

WITH cohort_year_ltv as
(
SELECT
  customerkey,
  EXTRACT( YEAR FROM MIN(orderdate))as cohort_year,
  SUM(quantity * netprice * exchangerate) as customer_ltv
FROM
  sales
GROUP BY customerkey
ORDER BY cohort_year, customerkey
),

cohort_summary as
(
SELECT
  customerkey,
  cohort_year,
  customer_ltv,
  AVG(customer_ltv) OVER(PARTITION BY cohort_year) AS avg_customer_ltv
FROM
  cohort_year_ltv
ORDER BY cohort_year, customerkey
),

cohort_final as
(
SELECT DISTINCT
  cohort_year,
  avg_customer_ltv
FROM
  cohort_summary
ORDER BY
  cohort_year
)

SELECT
  *,
  LAG(avg_customer_ltv) OVER(ORDER BY cohort_year) as previous_year_ltv,
 ((avg_customer_ltv -  LAG(avg_customer_ltv) OVER(ORDER BY cohort_year)) / LAG(avg_customer_ltv) OVER(ORDER BY cohort_year)) * 100 as rate_of_change
FROM
  cohort_final

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  cohort_year  avg_customer_ltv  previous_year_ltv  rate_of_change
0        2015           5271.59                NaN             NaN
1        2016           5404.92            5271.59            2.53
2        2017           5403.08            5404.92           -0.03
3        2018           4896.64            5403.08           -9.37
4        2019           4731.95            4896.64           -3.36
5        2020           3933.32            4731.95          -16.88
6        2021           3943.33            3933.32            0.25
7        2022           3315.52            3943.33          -15.92
8        2023           2543.18            3315.52          -23.29
9        2024           2037.55            2543.18          -19.88

In [ ]:
%%sql

WITH monthly_sales as
(
SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
  SUM(quantity * netprice * exchangerate) as net_revenue
FROM
  sales
WHERE TO_CHAR(orderdate, 'YYYY') = '2023'
GROUP BY order_month
ORDER BY order_month
)

SELECT
  order_month,
  net_revenue,
  AVG(net_revenue) OVER(ORDER BY order_month ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS two_month_running_avg,
  AVG(net_revenue) OVER(ORDER BY order_month ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) as three_month_running_avg,
  AVG(net_revenue) OVER( ORDER BY order_month) as running_average_to_date
FROM
  monthly_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,order_month,net_revenue,two_month_running_avg,three_month_running_avg,running_average_to_date
0,2023-01,3664431.34,3664431.34,4064817.96,3664431.34
1,2023-02,4465204.57,4064817.96,3457984.14,4064817.96
2,2023-03,2244316.52,3354760.54,2624105.75,3457984.14
3,2023-04,1162796.16,1703556.34,2116706.22,2884187.15
4,2023-05,2943005.99,2052901.08,2323434.06,2895950.92
5,2023-06,2864500.03,2903753.01,2715048.45,2890709.10
6,2023-07,2337639.34,2601069.68,2608686.39,2811699.14
7,2023-08,2623919.79,2480779.57,2528111.33,2788226.72
8,2023-09,2622774.85,2623347.32,2599339.08,2769843.18
9,2023-10,2551322.61,2587048.73,2624733.61,2747991.12
10,2023-11,2700103.38,2625712.99,2726658.97,2743637.69
11,2023-12,2928550.93,2814327.15,2814327.15,2759047.13