<a href="https://colab.research.google.com/github/dareoyeleke/SQL-ENGINEERING/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql

SELECT
  column_name
FROM
  information_schema.columns
WHERE
  table_schema = 'public'
AND
  table_name = 'customer';

SELECT
  COUNT(*) AS total_rows
FROM
  customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

1 rows affected.

   total_rows
0      104990

In [ ]:
%%sql

SELECT
  column_name
FROM
  information_schema.columns
WHERE
  table_schema = 'public'
AND
  table_name = 'sales'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

13 rows affected.

     column_name
0       orderkey
1     linenumber
2      orderdate
3   deliverydate
4    customerkey
5       storekey
6     productkey
7       quantity
8      unitprice
9       netprice
10      unitcost
11  currencycode
12  exchangerate

In [ ]:
%%sql

DROP VIEW customer_sales_data

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql
CREATE OR REPLACE VIEW customer_sales_data AS
WITH sales_data AS
(
SELECT
  customerkey,
  SUM(quantity * netprice * exchangerate) as net_revenue
FROM
  sales
GROUP BY
  customerkey
)

SELECT
  c.customerkey,
  sd.net_revenue
FROM
  customer c
LEFT JOIN
  sales_data sd
ON
  sd.customerkey = c.customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql

# COALESCE WORKS SIMILAR TO NULLIF
SELECT
  column_name
FROM
  information_schema.columns
WHERE
  table_schema = 'public'
AND
  table_name = 'customer_sales_data';


SELECT
  *
FROM
  customer_sales_data;

SELECT
  COUNT(*) AS null_value_rows
FROM
  customer_sales_data
WHERE
  net_revenue IS NULL;

SELECT
  customerkey,
  net_revenue,
  COALESCE(net_revenue, 0) AS net_revenue_filled
FROM
  customer_sales_data;
SELECT
  COUNT(*)
FROM
  customer_sales_data
WHERE
  COALESCE(net_revenue, 0) = 0;

SELECT
  AVG(net_revenue) AS spending_customer_net_revenue_avg,
  AVG(COALESCE(net_revenue, 0)) AS all_customers_net_revenue_avg
FROM
  customer_sales_data;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

104990 rows affected.

1 rows affected.

104990 rows affected.

1 rows affected.

1 rows affected.

   spending_customer_net_revenue_avg  all_customers_net_revenue_avg
0                            4170.94                        1965.97

In [ ]:
%%sql
# String formatting with LOWER, UPPER, CONCAT, TRIM.

SELECT
  LOWER('OLUWADAMILARE OYELEKE');

SELECT
  UPPER('oluwadamilare oyeleke');

SELECT
  TRIM('()' FROM '(Oluwadamilare Oyeleke)')

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

1 rows affected.

1 rows affected.

                   btrim
0  Oluwadamilare Oyeleke

In [ ]:
%%sql
CREATE OR REPLACE VIEW customer_name_order AS
WITH revenue_table as
(
SELECT
  customerkey,
  orderdate,
  SUM(quantity * netprice * exchangerate) as total_net_revenue,
  COUNT(orderkey) AS order_counts
FROM
  sales
GROUP BY customerkey, orderdate
)

SELECT
  rt.customerkey,
  rt.orderdate,
  rt.total_net_revenue,
  rt.order_counts,
  MIN(rt.orderdate) OVER(PARTITION BY rt.customerkey)AS first_purchase_date,
  EXTRACT(YEAR FROM MIN(rt.orderdate) OVER(PARTITION BY rt.customerkey)) as cohort_year ,
  c.countryfull,
  c.age,
  CONCAT(TRIM(c.givenname), ' ', TRIM(c.surname)) AS full_name
FROM
  revenue_table rt
LEFT JOIN customer c ON rt.customerkey = c.customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql

SELECT
  *
FROM
  customer_name_order;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

83099 rows affected.

,customerkey,orderdate,total_net_revenue,order_counts,first_purchase_date,cohort_year,countryfull,age,full_name
0,15,2021-03-08,2217.41,1,2021-03-08,2021,Australia,55,Julian McGuigan
1,180,2018-07-28,525.31,1,2018-07-28,2018,Australia,65,Gabriel Bosanquet
2,180,2023-08-28,1984.90,2,2018-07-28,2018,Australia,65,Gabriel Bosanquet
3,185,2019-06-01,1395.52,1,2019-06-01,2019,Australia,40,Gabrielle Castella
4,243,2016-05-19,287.67,1,2016-05-19,2016,Australia,66,Maya Atherton
...,...,...,...,...,...,...,...,...,...
83094,2099697,2022-09-13,38.20,3,2022-09-13,2022,United States,54,Phillipp Maier
83095,2099711,2016-08-13,2067.75,1,2016-08-13,2016,United States,80,Katerina Pavlícková
83096,2099711,2017-08-14,3940.92,1,2016-08-13,2016,United States,80,Katerina Pavlícková
83097,2099743,2022-03-17,469.62,2,2022-03-17,2022,United States,21,Luciana Almonte
83098,2099743,2023-02-11,598.46,1,2022-03-17,2022,United States,21,Luciana Almonte

In [ ]:
%%sql
WITH customer_lifetime_ltv AS
(
SELECT
  customerkey,
  full_name,
  SUM(total_net_revenue) AS total_customer_ltv
FROM
  customer_name_order
GROUP BY
  customerkey,
  full_name
ORDER BY
  total_customer_ltv
)

SELECT
  *,
  CASE
    WHEN total_customer_ltv < (PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_customer_ltv)) THEN '1 - Low-Value'
    WHEN total_customer_ltv >= (PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_customer_ltv)) AND total_customer_ltv < (PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY total_customer_ltv)) THEN '2 - Mid-Value'
    ELSE
      '3 - High-Value'
  END AS
    customer_Value
FROM
  customer_lifetime_ltv
GROUP BY
  customerkey,
  full_name,
  total_customer_ltv
ORDER BY
  total_customer_ltv

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey              full_name  total_customer_ltv  customer_value
0           612844         Heloise Busson                1.52  3 - High-Value
1           447646          Ralph Pfeffer                2.55  3 - High-Value
2           881751  Marein Schoonderwoerd                2.98  3 - High-Value
3          1035383           Elise Hughes                3.14  3 - High-Value
4          1064373             John Leach                3.27  3 - High-Value
...            ...                    ...                 ...             ...
49482       326979           Robert Young            61349.65  3 - High-Value
49483      1232832         James Thompson            62460.01  3 - High-Value
49484      1743963        Patricia Dalton            65431.98  3 - High-Value
49485       399184        Peter Rodriguez            79201.82  3 - High-Value
49486        72844          Ben Davenport            82057.67  3 - High-Value

[49487 rows x 4 columns]

In [ ]:

  CASE
    WHEN SUM(total_net_revenue) < (PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY SUM(total_net_revenue))) THEN '1 - Low-Value'
    WHEN SUM(total_net_revenue) >= (PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY SUM(total_net_revenue))) AND SUM(total_net_revenue) < (PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY SUM(total_net_revenue))) THEN '2 - Mid-Value'
    ELSE
      '3 - High-Value'
  END AS
    customer_Value